services:
  postgres:
    container_name: postgres-server
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - asoiaf_pg_data:/bitnami/postgresql

volumes:
  asoiaf_pg_data:
